### ISSUE TITLE
Bug: Can't set repository name.

### ISSUE THREAD

**Issue by metruzanca** [joshuakto/fit#11]
I have 122 (public + private) repos, but the api call only seems to show 50 or so. It would be nice to be able to enter the name of the repository as an option. On mobile I had to install a text editor so that I could update the `"repo":""` key in the `data.json`.

**Comment by ciriousjoker** [comment]
Same issue here, I only see a couple of repositories. Setting a name that is alphabetically "early", ie `a_my_obsidian_vault` or whatever shows it in the list correctly, but I'd like to not have that limitation.

**Comment by ciriousjoker** [comment]
Somewhat of a workaround:
1. Rename to "a_yourname"
2. Do the setup in fit (repo now shows up first)
3. Rename back (Github seems to keep old names indefinitely and redirect them to the current name)

**Comment by metruzanca** [comment]
> (Github seems to keep old names indefinitely and redirect them to the current name)

Yeah github does this to prevent breaking every contributors remote url, which is nice. It'll work so long as you don't make a new repo with the same name I thini.

**Comment by joshuakto** [comment]
thanks @anpigon for making the PR, the feature for showing more repos utilizing pagination is now in the pre-release version of the plugin, you can find the pre-release version [here](https://github.com/joshuakto/fit/releases).
To install the pre-release version, you need to download the following files
1. [main.js](https://github.com/joshuakto/fit/releases/download/1.1.1-repo-pagination/main.js)
2. [manifest.json](https://github.com/joshuakto/fit/releases/download/1.1.1-repo-pagination/manifest.json)
3. [styles.css](https://github.com/joshuakto/fit/releases/download/1.1.1-repo-pagination/styles.css)
, put them in the plugin's folder (.obsidian/plugins/fit) and then reload obsidian for the new script to be loaded

It'd be great if someone could reply in this thread after testing the pre-release (including your device type)

**Comment by MinSomai** [comment]
LGTM. tested in mac m2.
