### ISSUE TITLE
feature request: i18n/localization support

### ISSUE THREAD

**Issue by marat2509** [joshuakto/fit#15]
Hello. Thank you for your hard work and time invested. 

I want to ask you to implement localization support in the plugin so that it can be multilingual and be able to receive translations into different languages from the community. 

In turn, I will be one of the first to add a high-quality Russian translation to the plugin.

Thanks

**Comment by marat2509** [comment]
Up

**Comment by joshuakto** [comment]
Hi @marat2509 thanks for suggesting this! This is a good idea. I haven't had time to look into how we can incorporate i18n yet, if you could make a PR I'd be happy to review and incorporate the changes after some testing.
