### ISSUE TITLE
gitea support

### ISSUE THREAD

**Issue by DearFox** [joshuakto/fit#2]
I have a personal gitea instance that is always online, I think for some users who for some reason do not want or cannot use github this would be useful.
 Although I don't know for sure if gitea has similar api for this, but it sounds like it's true.

**Comment by joshuakto** [comment]
@DearFox thanks for the suggestion. I opened #4 to consolidate suggestions for supporting other git tools. Please feel free to post followup comments there, welcoming suggestions!
