### ISSUE TITLE
Crashing on mobile

### ISSUE THREAD

**Issue by freedomforwhat** [joshuakto/fit#30]
После настройки, по кнопке "fit sync"  начинает проверку "performing pre sync checks", и на этом крашится (стандартное уведомление Андроид «в работе приложения obsidian произошёл сбой») через секунд 30, и репозиторий по итогу не наполняется ничем, readme файл один как был, так и остаётся. Я могу как-то вытащить лог плагина/Обсидиана для вас?

Eng: After customization, on the "fit sync" button it starts "performing pre sync checks" and then crashes (standard Android notification "obsidian application failed") after 30 seconds, and the repository is not filled with anything, the readme file is the same as it was. Is there any way I can pull the plugin/obsidian log for you?
![Screenshot_20240919-085407](https://github.com/user-attachments/assets/f2623bf0-57c5-44fa-b4a0-c7aa571576a8)

**Comment by freedomforwhat** [comment]
![Screenshot_20240919-085551](https://github.com/user-attachments/assets/d4e885da-49c2-49dc-9259-3259670bf1e8)

**Comment by sviperz** [comment]
Same issue, except the first sync after setting everything up went good, but when I do "Fit Sync" from the menu the app is crashing.

Pixel 9, Android 14.

**Comment by perpleksed** [comment]
Same problem on Pixel 8 Pro
