### ISSUE TITLE
Support for other git based version control tools

### ISSUE THREAD

**Issue by joshuakto** [joshuakto/fit#4]
I think the best way to add support for other git-based version control tools (e.g., gitea, gitlab, etc.) would be to enable the initialization of the plugin with different fit classes. Each fit class would support a specific git tool (e.g. gitlab), and implement the IFit interface so it will work nicely with the plugin. This way, anyone in the community who would like to contribute to this plugin with a new tool support would be able to do so.
https://github.com/joshuakto/fit/blob/8878193d48d866a05dcd78f1599f4af068c69c5b/src/fit.ts#L9
If someone thinks of a better approach, please feel free to suggest them!

**Comment by joshuakto** [comment]
Ideally, the support for other git tools will not add to the size of the plugin and would only load the additional scripts as the user selects a new tool (e.g., from default GitHub -> Git Lab), if anyone have any ideas or inspirations from other plugins, please feel free to post them here.

**Comment by andrewcrook** [comment]
Gitea support as well including self hosting

**Comment by andrewcrook** [comment]
I really think this should remain open

**Comment by joshuakto** [comment]
reopening the issue for discussion
