### ISSUE TITLE
Crash when syncing on iOS

### ISSUE THREAD

**Issue by tbdcit** [joshuakto/fit#6]
Syncing from the desktop seems to be working fine but synchronising from mobile iOS triggers a crash which makes the obsidian app restart. 

I have tried in this on a vault with all other community plugins disabled.  Any suggestions as on how to debug this issue?

**Comment by joshuakto** [comment]
Have you updated to version 1.1.1? The earlier version had an issue because in iOS the [getFileByPath](https://docs.obsidian.md/Reference/TypeScript+API/Vault/getFileByPath) function will cause an error.
If your version is up to date, and the issue is not resolved, please provide steps to reproduce the error, thanks!

**Comment by tbdcit** [comment]
Yes I am on version 1.1.1

Maybe I am using the plugin incorrectly, what I tried was the following:

1. create a blank repository on GitHub
2. sync my vault to GitHub using this plugin
3. copy my vault to my phone manually
4. make changes to the vault on the phone
5. run fit sync

This caused the iOS app to crash. From here I tried

1. create an empty vault in iOS
2. Install the fit plugin and nothing else
3. synchronise with the existing repo containing my vault 

This causes the plugin to report “performing pre sync checks” and then “unable to sync…”

What is the correct way to use this plugin to sync between two devices?

**Comment by tbdcit** [comment]
Just to update that now fit is working with iOS, it seems that it was important to start with an empty vault, install the fit plugin and then sync with the existing vault on GitHub. I think that the reason that this approach was not working previously is that my internet connection was unstable - not an issue the plugin. 

The problem I was having originally seems to be that fIT is not working well when you try to synchronise two non-empty vaults, and this is the first time you synchronise these two vaults.
